### ISSUE TITLE
how to set the ignorePattern parameter?

### ISSUE THREAD

**Issue by huifan** [fcrespel/jenkins-cas-plugin#12]
CAS official client provides the parameter ignorePattern but our plug-in does not provide

ignorePattern | Defines the url pattern to ignore, when intercepting authentication requests.

**Comment by fcrespel** [comment]
This plugin does not intercept authentication requests like a regular Java application, this is handled by Jenkins itself. So the ignorePattern parameter you are referring to cannot be configured here. If you want to allow anonymous access to specific pages, you would need to find a way to do it with Jenkins security config (but I don't know how).
