### ISSUE TITLE
Recent cas upgrade break the connexion

### ISSUE THREAD

**Issue by flotho** [fcrespel/jenkins-cas-plugin#13]
Hi,

Thanks for your plugin, we've been using it without any issue for a long time. Recently we've upgraded CAS to the 6.6.7 release.
It's placed behind an apache RP and is using ldap as a athentication source.
The attribute cn is exposed and also configured in jenkins 2.405 and I'm experiencing something that looks like https://github.com/fcrespel/jenkins-cas-plugin/issues/9#issuecomment-455368534

here is the log I have in jenkins : 
```
2023-05-25 19:21:19.974+0000 [id=35604]        SEVERE        o.j.cas.client.util.CommonUtils#getResponseFromServer: Error getting response from host: [cas.....] with path: [/cas/p3/serviceValidate] and protocol: [https] Error Message: Server returned HTTP response code: 403 for URL: https://cas...../cas/p3/serviceValidate?ticket=ST-33-????????-sso&service=https%3A%2F%2Fjenkins.tld%2FsecurityRealm%2FfinishLogin
mai 25 19:21:19 jenkins jenkins[647557]: java.io.IOException: Server returned HTTP response code: 403 for URL: https://cas..../cas/p3/serviceValidate?ticket=ST-33-????????-sso&service=https%3A%2F%2Fjenkins.tld%2FsecurityRealm%2FfinishLogin
mai 25 19:21:19 jenkins jenkins[647557]:         at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)

```
could you tell me how to help you to identify what's going on ?
Regards

**Comment by fcrespel** [comment]
Hello @flotho, since Jenkins is getting a 403 error from CAS, you will likely find more details in the CAS logs. If the cause is not obvious, try increasing the log level on CAS to get additional details. Feel free to share them here if necessary.

**Comment by flotho** [comment]
Hi @fcrespel thanks for your answer , I'll provide more logs.

Regards
