### ISSUE TITLE
Compilation fails with latest version of jenkins

### ISSUE THREAD

**Issue by fbacchella** [fcrespel/jenkins-cas-plugin#5]
I'm using the latest git version.

If I change the parent version in the pom:

	<parent>
		<groupId>org.jenkins-ci.plugins</groupId>
		<artifactId>plugin</artifactId>
		<version>1.640</version>
	</parent>

I get:

    [ERROR] /private/tmp/cas-plugin/src/main/java/org/jenkinsci/plugins/cas/spring/CasEventListener.java:[3,19] error: cannot find symbol

with a `mvn clean package`

If I add:

		<dependency>
		    <groupId>org.jvnet.hudson.main</groupId>
		    <artifactId>hudson-core</artifactId>
		    <scope>provided</scope>
		    <version>2.2.1</version>
		</dependency>

I'm getting

    [INFO] -------------------------------------------------------------
    [ERROR] COMPILATION ERROR : 
    [INFO] -------------------------------------------------------------
    [ERROR] error: javax.annotation.processing.FilerException: Attempt to reopen a file for path /private/tmp/cas-plugin/target/classes/org/jenkinsci/plugins/cas/protocols/Cas20Protocol.stapler
    [INFO] 1 error
    [INFO] -------------------------------------------------------------

**Comment by fbacchella** [comment]
The last good version is 1.493

**Comment by sdorra** [comment]
@fbacchella i've created a fork of the plugin to add support for the CAS REST Protocol (see #6). In this fork i've bumped the version to 1.609.2.

**Comment by fcrespel** [comment]
This is resolved in version 1.3.0.
